<?php
/** Managed campaign slider — [alookhor_campaign_slider]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_campaign_defaults(){return ['enabled'=>true,'autoplay'=>true,'autoplay_interval'=>5500,'show_arrows'=>true,'show_dots'=>true,'height'=>420,'radius'=>24,'overlay'=>58,'background'=>'#100817','gold'=>'#D4AF37','text'=>'#FFFFFF','slides'=>[
 ['image_id'=>0,'image_url'=>'','image_alt'=>'کمپین آلوخور','eyebrow'=>'پیشنهاد ویژه آلوخور','title'=>'کمپین فروش ویژه','description'=>'بهترین محصولات آلوخور با شرایط ویژه','button_text'=>'مشاهده محصولات','button_url'=>'/shop/'],
 ['image_id'=>0,'image_url'=>'','image_alt'=>'خرید عمده آلوخور','eyebrow'=>'همکاری با کسب‌وکارها','title'=>'فروش عمده و صادراتی','description'=>'قیمت همکاری و تأمین پایدار محصولات','button_text'=>'درخواست همکاری','button_url'=>'/#b2b'],
]];}
function alookhor_cc_get_campaign_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['campaign_settings']??null)?$state['campaign_settings']:[];$s=array_replace_recursive(alookhor_cc_campaign_defaults(),$saved);$s['slides']=array_values(array_filter((array)$s['slides'],fn($x)=>is_array($x)&&!empty($x['image_url'])));return $s;}
function alookhor_cc_campaign_shortcode(){$s=alookhor_cc_get_campaign_settings();if(empty($s['enabled']))return '';$slides=(array)$s['slides'];if(!$slides)return '<div class="alookhor-campaign-empty">تصاویر کمپین را از مدیریت بوتیک انتخاب کنید</div>';$background=sanitize_hex_color($s['background']??'')?:'#100817';$gold=sanitize_hex_color($s['gold']??'')?:'#D4AF37';$text=sanitize_hex_color($s['text']??'')?:'#FFFFFF';ob_start();static $style=false;if(!$style){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-campaign-slider.css';if(file_exists($f))echo '<style id="alookhor-campaign-inline">'.file_get_contents($f).'</style>';}?>
<div class="alookhor-campaign-wrap" dir="rtl" style="--ac-bg:<?php echo esc_attr($background);?>"><section class="alookhor-campaign" dir="rtl" data-autoplay="<?php echo !empty($s['autoplay'])?'1':'0';?>" data-interval="<?php echo max(2500,min(15000,absint($s['autoplay_interval'])));?>" style="--ac-gold:<?php echo esc_attr($gold);?>;--ac-text:<?php echo esc_attr($text);?>;--ac-height:<?php echo max(260,min(700,absint($s['height'])));?>px;--ac-radius:<?php echo max(0,min(40,absint($s['radius'])));?>px;--ac-overlay:<?php echo max(0,min(90,absint($s['overlay'])))/100;?>"><div class="ac-track"><?php foreach($slides as $i=>$slide):?><article class="ac-slide<?php echo $i===0?' is-active':'';?>" style="--ac-image:url('<?php echo esc_url($slide['image_url']);?>')"><div class="ac-content"><span><?php echo esc_html($slide['eyebrow']??'');?></span><h2><?php echo esc_html($slide['title']??'');?></h2><p><?php echo esc_html($slide['description']??'');?></p><?php if(!empty($slide['button_text'])):?><a href="<?php echo esc_url($slide['button_url']??'');?>"><?php echo esc_html($slide['button_text']);?></a><?php endif;?></div></article><?php endforeach;?></div><?php if(count($slides)>1&&!empty($s['show_arrows'])):?><button class="ac-prev" type="button" aria-label="قبلی">‹</button><button class="ac-next" type="button" aria-label="بعدی">›</button><?php endif;?><?php if(count($slides)>1&&!empty($s['show_dots'])):?><div class="ac-dots"><?php foreach($slides as $i=>$_):?><button type="button" data-index="<?php echo $i;?>" class="<?php echo $i===0?'is-active':'';?>"></button><?php endforeach;?></div><?php endif;?></section></div><?php return ob_get_clean();}
add_shortcode('alookhor_campaign_slider','alookhor_cc_campaign_shortcode');add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-campaign',ALOOKHOR_CC_URL.'assets/css/frontend-campaign-slider.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-campaign',ALOOKHOR_CC_URL.'assets/js/frontend-campaign-slider.js',[],ALOOKHOR_CC_BUILD,true);});
