<?php
/** Professional contact page — [alookhor_contact_page]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_contact_url(){static $url=null;if($url!==null)return $url;$page=get_page_by_path('تماس-با-ما',OBJECT,'page');if(!$page)$page=get_page_by_title('تماس با ما',OBJECT,'page');$url=$page?get_permalink($page):home_url('/تماس-با-ما/');return $url;}
function alookhor_cc_contact_settings(){
 $header=function_exists('alookhor_cc_front_header_settings')?alookhor_cc_front_header_settings():[];$state=alookhor_cc_get_settings();$footer=(array)($state['footer_settings']??[]);
 return ['phone'=>$header['phone']??'','email'=>$header['email']??get_option('admin_email'),'whatsapp'=>$header['whatsapp_number']??'','address'=>$footer['address']??'خراسان رضوی، خور نیشابور','hours_week'=>$footer['hours_week']??'شنبه تا پنجشنبه: ۸ الی ۲۰','hours_friday'=>$footer['hours_friday']??'جمعه‌ها: ۹ الی ۱۴'];
}
function alookhor_cc_contact_icon($name){$p=['phone'=>'<path d="M6.6 2.8 9.4 2c.6-.2 1.2.1 1.4.7L12 5.9c.2.5 0 1-.4 1.3L10 8.4c.9 1.9 2.5 3.5 4.4 4.4l1.2-1.6c.3-.4.8-.6 1.3-.4l3.2 1.2c.6.2.9.8.7 1.4l-.8 2.8c-.2.6-.7 1-1.4 1C10 17.2 4.8 11.9 4.8 4.2c0-.7.4-1.2 1.1-1.4Z"/>','email'=>'<path d="M3 5h18v14H3zM3 7l9 6 9-6"/>','pin'=>'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>','clock'=>'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>','whatsapp'=>'<circle cx="12" cy="12" r="9"/><path d="M8 18 5 19l1-3a7 7 0 1 1 2 2Z"/>','send'=>'<path d="m22 2-7 20-4-9-9-4 20-7Z"/><path d="M22 2 11 13"/>'];return '<svg viewBox="0 0 24 24" aria-hidden="true">'.($p[$name]??$p['send']).'</svg>';}
function alookhor_cc_contact_shortcode(){
 $c=alookhor_cc_contact_settings();$phone_href=preg_replace('/[^0-9+]/','',(string)$c['phone']);$wa=preg_replace('/\D+/','',(string)$c['whatsapp']);
 ob_start();?>
<section class="alookhor-contact" dir="rtl"><div class="act-inner"><header><span>CONTACT ALOOKHOR</span><h1>با آلوخور در ارتباط باشید</h1><p>برای خرید، سفارش عمده، صادرات یا پشتیبانی پیام بفرستید؛ تیم آلوخور در سریع‌ترین زمان پاسخ می‌دهد.</p></header><div class="act-layout"><aside class="act-info"><div class="act-brand"><b>آلوخور</b><small>از خور به جهان</small></div><h2>راه‌های ارتباط مستقیم</h2><p>برای دریافت مشاوره تخصصی، استعلام قیمت و پیگیری سفارش از مسیر مناسب با ما تماس بگیرید.</p><div class="act-cards"><?php if($c['phone']):?><a href="tel:<?php echo esc_attr($phone_href);?>"><i><?php echo alookhor_cc_contact_icon('phone');?></i><span><small>تلفن تماس</small><b dir="ltr"><?php echo esc_html($c['phone']);?></b></span></a><?php endif;?><?php if($c['email']):?><a href="mailto:<?php echo esc_attr($c['email']);?>"><i><?php echo alookhor_cc_contact_icon('email');?></i><span><small>ایمیل</small><b dir="ltr"><?php echo esc_html($c['email']);?></b></span></a><?php endif;?><div><i><?php echo alookhor_cc_contact_icon('pin');?></i><span><small>نشانی</small><b><?php echo esc_html($c['address']);?></b></span></div><div><i><?php echo alookhor_cc_contact_icon('clock');?></i><span><small>ساعت پاسخ‌گویی</small><b><?php echo esc_html($c['hours_week']);?><br><?php echo esc_html($c['hours_friday']);?></b></span></div></div><?php if($wa):?><a class="act-whatsapp" href="https://wa.me/<?php echo esc_attr($wa);?>" target="_blank" rel="noopener"><?php echo alookhor_cc_contact_icon('whatsapp');?><span>گفت‌وگوی مستقیم در واتساپ</span></a><?php endif;?></aside><form class="act-form" novalidate><div class="act-form-head"><span>ارسال پیام</span><h2>چطور می‌توانیم کمک کنیم؟</h2><p>اطلاعات زیر را کامل کنید؛ پاسخ برای شما ارسال خواهد شد.</p></div><div class="act-grid"><label>نام و نام خانوادگی<input name="name" required minlength="2" autocomplete="name" placeholder="نام شما"></label><label>شماره تماس<input name="phone" required inputmode="tel" autocomplete="tel" dir="ltr" placeholder="09xxxxxxxxx"></label><label>ایمیل<input name="email" type="email" autocomplete="email" dir="ltr" placeholder="name@example.com"></label><label>موضوع<select name="subject" required><option value="">انتخاب کنید</option><option>خرید محصول</option><option>سفارش عمده</option><option>صادرات</option><option>پیگیری سفارش</option><option>پشتیبانی</option></select></label><label class="act-full">پیام شما<textarea name="message" required minlength="10" rows="5" placeholder="لطفاً درخواست خود را کامل بنویسید…"></textarea></label></div><input class="act-hp" name="website" tabindex="-1" autocomplete="off"><label class="act-consent"><input type="checkbox" required> با ثبت فرم، با پردازش اطلاعات برای پاسخ‌گویی موافقم.</label><button type="submit"><?php echo alookhor_cc_contact_icon('send');?><span>ارسال پیام</span></button><p class="act-message" aria-live="polite"></p><input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('alookhor_contact'));?>"></form></div></div></section>
<?php return ob_get_clean();}
add_shortcode('alookhor_contact_page','alookhor_cc_contact_shortcode');
add_action('wp_ajax_alookhor_contact_submit','alookhor_cc_contact_submit');add_action('wp_ajax_nopriv_alookhor_contact_submit','alookhor_cc_contact_submit');
function alookhor_cc_contact_submit(){check_ajax_referer('alookhor_contact','nonce');if(!empty($_POST['website']))wp_send_json_success(['message'=>'پیام ثبت شد.']);$ip=sanitize_text_field($_SERVER['REMOTE_ADDR']??'unknown');$rate='alookhor_contact_'.md5($ip);if(get_transient($rate))wp_send_json_error(['message'=>'لطفاً کمی بعد دوباره تلاش کنید.'],429);$name=sanitize_text_field(wp_unslash($_POST['name']??''));$phone=sanitize_text_field(wp_unslash($_POST['phone']??''));$email=sanitize_email(wp_unslash($_POST['email']??''));$subject=sanitize_text_field(wp_unslash($_POST['subject']??''));$message=sanitize_textarea_field(wp_unslash($_POST['message']??''));if(strlen($name)<2||!preg_match('/^[+0-9۰-۹\s-]{10,20}$/u',$phone)||strlen($message)<10)wp_send_json_error(['message'=>'نام، تلفن و متن پیام را صحیح وارد کنید.'],422);$id=wp_insert_post(['post_type'=>'alookhor_contact','post_status'=>'private','post_title'=>$subject.' — '.$name,'post_content'=>$message],true);if(is_wp_error($id))wp_send_json_error(['message'=>'ثبت پیام انجام نشد؛ دوباره تلاش کنید.'],500);update_post_meta($id,'contact_name',$name);update_post_meta($id,'contact_phone',$phone);update_post_meta($id,'contact_email',$email);update_post_meta($id,'contact_subject',$subject);set_transient($rate,1,MINUTE_IN_SECONDS);wp_mail(get_option('admin_email'),'پیام جدید سایت آلوخور: '.$subject,"نام: $name\nتلفن: $phone\nایمیل: $email\n\n$message");wp_send_json_success(['message'=>'پیام شما با موفقیت ثبت شد. به‌زودی با شما تماس می‌گیریم.']);}
add_action('init',function(){register_post_type('alookhor_contact',['labels'=>['name'=>'پیام‌های تماس','singular_name'=>'پیام تماس'],'public'=>false,'show_ui'=>true,'show_in_menu'=>'alookhor-control-center','supports'=>['title','editor'],'capability_type'=>'post']);});

/** Replace the obsolete demo contact page once, with a reversible backup. */
add_action('init',function(){
 if(get_option('alookhor_contact_page_schema')==='1')return;
 $page=get_page_by_path('تماس-با-ما',OBJECT,'page');if(!$page)$page=get_page_by_title('تماس با ما',OBJECT,'page');
 if(!$page){$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'تماس با ما','post_name'=>'تماس-با-ما','post_content'=>'[alookhor_contact_page]']);$page=$id?get_post($id):null;}
 if($page){if(!get_post_meta($page->ID,'_alookhor_contact_backup',true))update_post_meta($page->ID,'_alookhor_contact_backup',['content'=>$page->post_content,'elementor_data'=>get_post_meta($page->ID,'_elementor_data',true),'saved_at'=>current_time('mysql')]);wp_update_post(['ID'=>$page->ID,'post_title'=>'تماس با ما','post_content'=>'[alookhor_contact_page]']);delete_post_meta($page->ID,'_elementor_data');delete_post_meta($page->ID,'_elementor_edit_mode');update_option('alookhor_contact_page_id',(int)$page->ID,false);}
 update_option('alookhor_contact_page_schema','1',false);
},40);
add_filter('nav_menu_link_attributes',function($atts,$item){$label=wp_strip_all_tags($item->title??'');$href=(string)($atts['href']??'');if(str_contains($label,'تماس با ما')||preg_match('~/contact/?$~i',$href)||str_contains($href,'تماس-با-ما'))$atts['href']=alookhor_cc_contact_url();return $atts;},20,2);
add_action('template_redirect',function(){if(trim((string)($_SERVER['REQUEST_URI']??''),'/')==='contact'){wp_safe_redirect(alookhor_cc_contact_url(),301);exit;}});
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-contact',ALOOKHOR_CC_URL.'assets/css/frontend-contact-page.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-contact',ALOOKHOR_CC_URL.'assets/js/frontend-contact-page.js',[],ALOOKHOR_CC_BUILD,true);wp_localize_script('alookhor-cc-contact','ALOOKHOR_CONTACT',['ajax_url'=>admin_url('admin-ajax.php'),'contact_url'=>alookhor_cc_contact_url()]);});
