<?php
/** Managed WooCommerce featured products — [alookhor_featured_products]. */
if (!defined('ABSPATH')) exit;
function alookhor_cc_featured_products_defaults(){return [
 'enabled'=>true,'title'=>'محصولات منتخب آلوخور','subtitle'=>'انتخابی از بهترین محصولات طبیعی و صادراتی','limit'=>8,'autoplay'=>true,'autoplay_interval'=>4500,'show_arrows'=>true,'show_price'=>true,'show_add_to_cart'=>true,'button_text'=>'مشاهده همه محصولات','button_url'=>'/shop/','background'=>'#0B0710','card'=>'#181020','gold'=>'#D4AF37','text'=>'#FFFFFF','muted'=>'#B8B0BD','radius'=>20,
];}
function alookhor_cc_get_featured_products_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['featured_product_settings']??null)?$state['featured_product_settings']:[];return array_replace(alookhor_cc_featured_products_defaults(),$saved);}
function alookhor_cc_featured_products_shortcode(){
 $s=alookhor_cc_get_featured_products_settings();if(empty($s['enabled'])||!function_exists('wc_get_products'))return '';
 $limit=max(4,min(16,absint($s['limit']??8)));$products=wc_get_products(['status'=>'publish','limit'=>$limit,'featured'=>true,'orderby'=>'date','order'=>'DESC']);
 if(!$products)$products=wc_get_products(['status'=>'publish','limit'=>$limit,'orderby'=>'date','order'=>'DESC']);if(!$products)return '';
 $c=[];foreach(['background','card','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_featured_products_defaults()[$k];
 ob_start();static $style=false;if(!$style){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-featured-products.css';if(file_exists($f))echo '<style id="alookhor-featured-products-inline">'.file_get_contents($f).'</style>';}?>
<section class="alookhor-fp" dir="rtl" data-autoplay="<?php echo !empty($s['autoplay'])?'1':'0';?>" data-interval="<?php echo max(2500,min(15000,absint($s['autoplay_interval'])));?>" style="--afp-bg:<?php echo esc_attr($c['background']);?>;--afp-card:<?php echo esc_attr($c['card']);?>;--afp-gold:<?php echo esc_attr($c['gold']);?>;--afp-text:<?php echo esc_attr($c['text']);?>;--afp-muted:<?php echo esc_attr($c['muted']);?>;--afp-radius:<?php echo max(10,min(36,absint($s['radius']??20)));?>px">
 <div class="afp-inner"><header><div><span>ALOOKHOR SELECTION</span><h2><?php echo esc_html($s['title']);?></h2><p><?php echo esc_html($s['subtitle']);?></p></div><?php if(!empty($s['button_text'])):?><a href="<?php echo esc_url($s['button_url']);?>"><?php echo esc_html($s['button_text']);?></a><?php endif;?></header><div class="afp-viewport"><div class="afp-track"><?php foreach($products as $product):$id=$product->get_id();?><article class="afp-card"><a class="afp-image" href="<?php echo esc_url(get_permalink($id));?>"><?php echo $product->get_image('woocommerce_thumbnail',['loading'=>'lazy']);?></a><div class="afp-body"><h3><a href="<?php echo esc_url(get_permalink($id));?>"><?php echo esc_html($product->get_name());?></a></h3><?php if(!empty($s['show_price'])):?><div class="afp-price"><?php echo wp_kses_post($product->get_price_html());?></div><?php endif;?><?php if(!empty($s['show_add_to_cart'])):?><a class="afp-cart" href="<?php echo esc_url($product->add_to_cart_url());?>" data-product_id="<?php echo esc_attr($id);?>"><?php echo esc_html($product->add_to_cart_text());?></a><?php endif;?></div></article><?php endforeach;?></div><?php if(count($products)>4&&!empty($s['show_arrows'])):?><button class="afp-prev" aria-label="قبلی" type="button">‹</button><button class="afp-next" aria-label="بعدی" type="button">›</button><?php endif;?></div></div>
</section><?php return ob_get_clean();}
add_shortcode('alookhor_featured_products','alookhor_cc_featured_products_shortcode');
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-featured-products',ALOOKHOR_CC_URL.'assets/css/frontend-featured-products.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-featured-products',ALOOKHOR_CC_URL.'assets/js/frontend-featured-products.js',[],ALOOKHOR_CC_BUILD,true);});
