<?php
/** Luxury WooCommerce collection — [alookhor_featured_products]. */
if (!defined('ABSPATH')) exit;
function alookhor_cc_featured_products_defaults(){return [
 'enabled'=>true,'eyebrow'=>'ALOOKHOR PREMIUM COLLECTION','title'=>'مجموعه منتخب','title_highlight'=>'آلوخور','subtitle'=>'دست‌چین بهترین آلوهای ایران | کیفیت ممتاز، طعم اصیل','limit'=>8,'autoplay'=>true,'autoplay_interval'=>4500,'show_arrows'=>true,'show_price'=>true,'show_rating'=>true,'show_excerpt'=>true,'show_badge'=>true,'show_add_to_cart'=>true,'product_button_text'=>'مشاهده محصول','button_text'=>'مشاهده کل مجموعه','button_url'=>'/shop/','background'=>'#1C1025','card'=>'#26213D','gold'=>'#D4AF37','text'=>'#FFFFFF','muted'=>'#E5E5E5','radius'=>20,
];}
function alookhor_cc_get_featured_products_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['featured_product_settings']??null)?$state['featured_product_settings']:[];return array_replace(alookhor_cc_featured_products_defaults(),$saved);}
function alookhor_cc_featured_products_shortcode(){
 $s=alookhor_cc_get_featured_products_settings();if(empty($s['enabled'])||!function_exists('wc_get_products'))return '';
 $limit=max(4,min(16,absint($s['limit']??8)));$products=wc_get_products(['status'=>'publish','limit'=>$limit,'featured'=>true,'orderby'=>'date','order'=>'DESC']);if(!$products)$products=wc_get_products(['status'=>'publish','limit'=>$limit,'orderby'=>'date','order'=>'DESC']);if(!$products)return '';
 $c=[];foreach(['background','card','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_featured_products_defaults()[$k];
 ob_start();static $style=false;if(!$style && alookhor_cc_should_inline_shortcode_css()){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-featured-products.css';if(file_exists($f))echo '<style id="alookhor-featured-products-inline">'.file_get_contents($f).'</style>';}?>
<section class="alookhor-fp" dir="rtl" data-autoplay="<?php echo !empty($s['autoplay'])?'1':'0';?>" data-interval="<?php echo max(2500,min(15000,absint($s['autoplay_interval'])));?>" style="--afp-bg:<?php echo esc_attr($c['background']);?>;--afp-card:<?php echo esc_attr($c['card']);?>;--afp-gold:<?php echo esc_attr($c['gold']);?>;--afp-text:<?php echo esc_attr($c['text']);?>;--afp-muted:<?php echo esc_attr($c['muted']);?>;--afp-radius:<?php echo max(10,min(36,absint($s['radius']??20)));?>px">
 <div class="afp-decor afp-decor-right" aria-hidden="true"></div><div class="afp-decor afp-decor-left" aria-hidden="true"></div>
 <div class="afp-inner"><header><span class="afp-crown" aria-hidden="true">♛</span><small><?php echo esc_html($s['eyebrow']);?></small><h2><?php echo esc_html($s['title']);?> <strong><?php echo esc_html($s['title_highlight']);?></strong></h2><p><?php echo esc_html($s['subtitle']);?></p><i aria-hidden="true"></i></header>
 <div class="afp-viewport"><div class="afp-track"><?php $badges=['ارگانیک','ویژه','صادراتی','پرفروش'];foreach($products as $index=>$product):$id=$product->get_id();$rating=(float)$product->get_average_rating();$reviews=(int)$product->get_review_count();$desc=wp_trim_words(wp_strip_all_tags($product->get_short_description()?:$product->get_description()),18,'…');?>
  <article class="afp-card"><div class="afp-card-glow" aria-hidden="true"></div><a class="afp-image" href="<?php echo esc_url(get_permalink($id));?>"><?php echo $product->get_image('woocommerce_thumbnail',['loading'=>'lazy']);?><?php if(!empty($s['show_badge'])):?><span><?php echo esc_html($badges[$index%4]);?></span><?php endif;?></a><div class="afp-body"><h3><a href="<?php echo esc_url(get_permalink($id));?>"><?php echo esc_html($product->get_name());?></a></h3><?php if(!empty($s['show_rating'])):?><div class="afp-rating" aria-label="امتیاز <?php echo esc_attr($rating);?> از ۵"><b>★ <?php echo esc_html(number_format_i18n($rating,1));?></b><small>(<?php echo esc_html(number_format_i18n($reviews));?> نظر)</small></div><?php endif;?><?php if(!empty($s['show_excerpt'])&&$desc):?><p><?php echo esc_html($desc);?></p><?php endif;?><?php if(!empty($s['show_price'])):?><div class="afp-price"><?php echo wp_kses_post($product->get_price_html());?><small>تومان / کیلو</small></div><?php endif;?><?php if(!empty($s['show_add_to_cart'])):?><a class="afp-cart" href="<?php echo esc_url(get_permalink($id));?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 8h12l-1 13H7L6 8Zm3 0V6a3 3 0 0 1 6 0v2"/></svg><?php echo esc_html($s['product_button_text']);?></a><?php endif;?></div></article>
 <?php endforeach;?></div><?php if(count($products)>4&&!empty($s['show_arrows'])):?><button class="afp-prev" aria-label="محصول قبلی" type="button">‹</button><button class="afp-next" aria-label="محصول بعدی" type="button">›</button><?php endif;?></div>
 <?php if(!empty($s['button_text'])):?><a class="afp-collection-cta" href="<?php echo esc_url($s['button_url']);?>"><span>♜</span><b><?php echo esc_html($s['button_text']);?></b><small>EXPLORE COLLECTION</small></a><?php endif;?></div>
</section><?php return ob_get_clean();}
add_shortcode('alookhor_featured_products','alookhor_cc_featured_products_shortcode');
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-featured-products',ALOOKHOR_CC_URL.'assets/css/frontend-featured-products.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-featured-products',ALOOKHOR_CC_URL.'assets/js/frontend-featured-products.js',[],ALOOKHOR_CC_BUILD,true);});
