<?php
/** International quality standards — [alookhor_international_standards]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_standards_defaults(){return ['enabled'=>true,'eyebrow'=>'TRUSTED WORLDWIDE','title'=>'استانداردهای بین‌المللی','title_highlight'=>'کیفیت','subtitle'=>'محصولات ما مطابق معتبرترین استانداردهای جهانی تولید، بسته‌بندی و کنترل کیفیت می‌شوند.','background'=>'#0B0716','card'=>'#12091A','gold'=>'#D4A436','text'=>'#FFFFFF','muted'=>'#C8BDCC','radius'=>18,'mobile_cta_title'=>'اعتماد شما سرمایه ماست','mobile_cta_text'=>'با تضمین کیفیت و استانداردهای بین‌المللی، بهترین محصولات خشکبار را به شما ارائه می‌دهیم.','mobile_cta_image'=>ALOOKHOR_CC_URL.'assets/images/category-nuts.jpg','items'=>[
 ['icon'=>'globe','title'=>'ISO 9001','description'=>'سیستم مدیریت کیفیت تولید صادراتی'],['icon'=>'shield','title'=>'HACCP','description'=>'سیستم مدیریت ایمنی مواد غذایی'],['icon'=>'organic','title'=>'ORGANIC','description'=>'محصول کاملاً ارگانیک و بدون افزودنی'],['icon'=>'halal','title'=>'HALAL','description'=>'گواهینامه حلال برای بازارهای بین‌المللی'],['icon'=>'info','title'=>'FDA','description'=>'تأییدشده توسط سازمان غذا و داروی ایالات متحده آمریکا'],['icon'=>'document','title'=>'GMP','description'=>'کنترل کیفی و بهداشتی فرآیند تولید']], 'stats'=>[
 ['icon'=>'users','value'=>'98%','label'=>'رضایت مشتریان صادراتی'],['icon'=>'medal','value'=>'+15','label'=>'سال سابقه و اعتبار تجاری'],['icon'=>'globe','value'=>'+25','label'=>'کشورهای هدف صادرات'],['icon'=>'shield','value'=>'100%','label'=>'تضمین ارگانیک و سلامت بار']]];}
function alookhor_cc_get_standards_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['standards_settings']??null)?$state['standards_settings']:[];$settings=array_replace_recursive(alookhor_cc_standards_defaults(),$saved);if(trim((string)($settings['title']??''))==='استانداردهای بین‌المللی کیفیت')$settings['title']='استانداردهای بین‌المللی';if(trim((string)($settings['mobile_cta_image']??''))==='')$settings['mobile_cta_image']=alookhor_cc_standards_defaults()['mobile_cta_image'];return $settings;}
function alookhor_cc_standard_icon($name){$p=['shield'=>'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>','info'=>'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>','organic'=>'<path d="M12 21V10M12 16c-6 0-9-4-9-9 6 0 9 4 9 9Zm0-4c0-6 4-9 9-9 0 6-4 9-9 9Z"/>','halal'=>'<path d="M18 3a9 9 0 1 0 3 15A8 8 0 1 1 18 3Z"/><path d="m8 12 2 2 5-5"/>','document'=>'<path d="M6 2h9l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/>','globe'=>'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 4 6 4 9s-1 6-4 9c-3-3-4-6-4-9s1-6 4-9Z"/>','users'=>'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>','medal'=>'<circle cx="12" cy="9" r="6"/><path d="m8 14-1 8 5-3 5 3-1-8M9 9h6"/>'];return '<svg viewBox="0 0 24 24">'.($p[$name]??$p['shield']).'</svg>';}
function alookhor_cc_standards_shortcode(){$s=alookhor_cc_get_standards_settings();if(empty($s['enabled']))return '';$c=[];foreach(['background','card','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_standards_defaults()[$k];ob_start();static $style=false;if(!$style){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-international-standards.css';if(alookhor_cc_should_inline_shortcode_css()&&file_exists($f))echo '<style id="alookhor-standards-inline">'.file_get_contents($f).'</style>';elseif(wp_doing_ajax()||is_admin())echo '<link rel="stylesheet" id="alookhor-standards-editor-css" href="'.esc_url(ALOOKHOR_CC_URL.'assets/css/frontend-international-standards.css?ver='.ALOOKHOR_CC_BUILD).'">';}?>
<section class="alookhor-standards" dir="rtl" style="--ast-bg:<?php echo esc_attr($c['background']);?>;--ast-card:<?php echo esc_attr($c['card']);?>;--ast-gold:<?php echo esc_attr($c['gold']);?>;--ast-text:<?php echo esc_attr($c['text']);?>;--ast-muted:<?php echo esc_attr($c['muted']);?>;--ast-radius:<?php echo max(12,min(32,absint($s['radius'])));?>px"><div class="ast-inner"><header><span>♛</span><small><?php echo esc_html($s['eyebrow']);?></small><h2><?php echo esc_html($s['title']);?> <strong><?php echo esc_html($s['title_highlight']??'');?></strong></h2><div><i></i><b>✦</b><p><?php echo esc_html($s['subtitle']);?></p><b>✦</b><i></i></div></header><div class="ast-grid"><?php foreach((array)$s['items'] as $item):?><article><i><?php echo alookhor_cc_standard_icon($item['icon']??'shield');?></i><h3><?php echo esc_html($item['title']??'');?></h3><b class="ast-card-divider" aria-hidden="true">◆</b><p><?php echo esc_html($item['description']??'');?></p></article><?php endforeach;?></div><div class="ast-stats"><?php foreach((array)$s['stats'] as $stat):if(empty($stat['value']))continue;?><span><i><?php echo alookhor_cc_standard_icon($stat['icon']??'shield');?></i><b><?php echo esc_html($stat['value']);?></b><small><?php echo esc_html($stat['label']??'');?></small></span><?php endforeach;?></div><aside class="ast-mobile-trust"><img src="<?php echo esc_url($s['mobile_cta_image']??'');?>" alt="محصولات ممتاز آلوخور" loading="lazy"><div><span>♛</span><h3><?php echo esc_html($s['mobile_cta_title']??'');?></h3><p><?php echo esc_html($s['mobile_cta_text']??'');?></p></div></aside></div></section><?php return ob_get_clean();}
add_shortcode('alookhor_international_standards','alookhor_cc_standards_shortcode');add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-standards',ALOOKHOR_CC_URL.'assets/css/frontend-international-standards.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-standards',ALOOKHOR_CC_URL.'assets/js/frontend-international-standards.js',[],ALOOKHOR_CC_BUILD,true);});
