<?php
/** International quality standards — [alookhor_international_standards]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_standards_defaults(){return ['enabled'=>true,'eyebrow'=>'TRUSTED WORLDWIDE','title'=>'استانداردهای بین‌المللی کیفیت','subtitle'=>'محصولات آلوخور مطابق معتبرترین استانداردهای جهانی تولید، بسته‌بندی و کنترل کیفیت می‌شوند','background'=>'#0B0716','card'=>'#12091A','gold'=>'#D4A436','text'=>'#FFFFFF','muted'=>'#C8BDCC','radius'=>18,'items'=>[
 ['icon'=>'shield','title'=>'ISO 9001','description'=>'سیستم مدیریت کیفیت تولید صادراتی'],['icon'=>'info','title'=>'HACCP','description'=>'سیستم مدیریت امنیت مواد غذایی'],['icon'=>'organic','title'=>'ORGANIC','description'=>'محصول کاملاً طبیعی و بدون افزودنی'],['icon'=>'halal','title'=>'HALAL','description'=>'تضمین تولید مطابق استانداردهای حلال'],['icon'=>'info','title'=>'FDA','description'=>'مورد تأیید سازمان غذا و داروی آمریکا'],['icon'=>'document','title'=>'GMP','description'=>'کنترل کیفی و بهداشتی فرآوری بار']], 'stats'=>[
 ['value'=>'98%','label'=>'رضایت مشتریان صادراتی'],['value'=>'+15','label'=>'سال سابقه و اعتبار تجاری'],['value'=>'+25','label'=>'کشورهای هدف صادرات'],['value'=>'100%','label'=>'تضمین ارگانیک و سورت بار']]];}
function alookhor_cc_get_standards_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['standards_settings']??null)?$state['standards_settings']:[];return array_replace_recursive(alookhor_cc_standards_defaults(),$saved);}
function alookhor_cc_standard_icon($name){$p=['shield'=>'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>','info'=>'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>','organic'=>'<path d="M12 21V10M12 16c-6 0-9-4-9-9 6 0 9 4 9 9Zm0-4c0-6 4-9 9-9 0 6-4 9-9 9Z"/>','halal'=>'<path d="M18 3a9 9 0 1 0 3 15A8 8 0 1 1 18 3Z"/><path d="m8 12 2 2 5-5"/>','document'=>'<path d="M6 2h9l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/>'];return '<svg viewBox="0 0 24 24">'.($p[$name]??$p['shield']).'</svg>';}
function alookhor_cc_standards_shortcode(){$s=alookhor_cc_get_standards_settings();if(empty($s['enabled']))return '';$c=[];foreach(['background','card','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_standards_defaults()[$k];ob_start();static $style=false;if(!$style){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-international-standards.css';if(alookhor_cc_should_inline_shortcode_css()&&file_exists($f))echo '<style id="alookhor-standards-inline">'.file_get_contents($f).'</style>';elseif(wp_doing_ajax()||is_admin())echo '<link rel="stylesheet" id="alookhor-standards-editor-css" href="'.esc_url(ALOOKHOR_CC_URL.'assets/css/frontend-international-standards.css?ver='.ALOOKHOR_CC_BUILD).'">';}?>
<section class="alookhor-standards" dir="rtl" style="--ast-bg:<?php echo esc_attr($c['background']);?>;--ast-card:<?php echo esc_attr($c['card']);?>;--ast-gold:<?php echo esc_attr($c['gold']);?>;--ast-text:<?php echo esc_attr($c['text']);?>;--ast-muted:<?php echo esc_attr($c['muted']);?>;--ast-radius:<?php echo max(12,min(32,absint($s['radius'])));?>px"><div class="ast-inner"><header><span>♛</span><small><?php echo esc_html($s['eyebrow']);?></small><h2><?php echo esc_html($s['title']);?></h2><div><i></i><b>✦</b><p><?php echo esc_html($s['subtitle']);?></p><b>✦</b><i></i></div></header><div class="ast-grid"><?php foreach((array)$s['items'] as $item):?><article><i><?php echo alookhor_cc_standard_icon($item['icon']??'shield');?></i><h3><?php echo esc_html($item['title']??'');?></h3><p><?php echo esc_html($item['description']??'');?></p></article><?php endforeach;?></div><div class="ast-stats"><?php foreach((array)$s['stats'] as $stat):if(empty($stat['value']))continue;?><span><b><?php echo esc_html($stat['value']);?></b><small><?php echo esc_html($stat['label']??'');?></small></span><?php endforeach;?></div></div></section><?php return ob_get_clean();}
add_shortcode('alookhor_international_standards','alookhor_cc_standards_shortcode');add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-standards',ALOOKHOR_CC_URL.'assets/css/frontend-international-standards.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-standards',ALOOKHOR_CC_URL.'assets/js/frontend-international-standards.js',[],ALOOKHOR_CC_BUILD,true);});
