<?php
/** WordPress magazine carousel — [alookhor_magazine]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_magazine_defaults(){return ['enabled'=>true,'title'=>'مجله آلوخور','subtitle'=>'آخرین مطالب درباره خواص، نگهداری، صادرات و فرآوری خشکبار','limit'=>8,'category_id'=>0,'autoplay'=>true,'autoplay_interval'=>5500,'show_arrows'=>true,'show_date'=>true,'show_excerpt'=>true,'show_like'=>true,'show_save'=>true,'button_text'=>'ادامه مطلب','background'=>'#0B0713','card'=>'#1A1027','gold'=>'#D4AF37','text'=>'#FFFFFF','muted'=>'#B8B0BD','radius'=>20];}
function alookhor_cc_get_magazine_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['magazine_settings']??null)?$state['magazine_settings']:[];return array_replace(alookhor_cc_magazine_defaults(),$saved);}
function alookhor_cc_magazine_shortcode(){$s=alookhor_cc_get_magazine_settings();if(empty($s['enabled']))return '';$args=['post_type'=>'post','post_status'=>'publish','posts_per_page'=>max(4,min(20,absint($s['limit']))),'ignore_sticky_posts'=>true];if(absint($s['category_id']))$args['cat']=absint($s['category_id']);$q=new WP_Query($args);if(!$q->have_posts())return '<div class="alookhor-mag-empty">هنوز نوشته‌ای برای مجله منتشر نشده است.</div>';$c=[];foreach(['background','card','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_magazine_defaults()[$k];ob_start();static $style=false;if(!$style && alookhor_cc_should_inline_shortcode_css()){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-magazine.css';if(file_exists($f))echo '<style id="alookhor-magazine-inline">'.file_get_contents($f).'</style>';}?>
<section class="alookhor-mag" dir="rtl" data-autoplay="<?php echo !empty($s['autoplay'])?'1':'0';?>" data-interval="<?php echo max(2500,min(15000,absint($s['autoplay_interval'])));?>" style="--am-bg:<?php echo esc_attr($c['background']);?>;--am-card:<?php echo esc_attr($c['card']);?>;--am-gold:<?php echo esc_attr($c['gold']);?>;--am-text:<?php echo esc_attr($c['text']);?>;--am-muted:<?php echo esc_attr($c['muted']);?>;--am-radius:<?php echo max(10,min(36,absint($s['radius'])));?>px"><div class="am-inner"><header><div><span>ALOOKHOR JOURNAL</span><h2><?php echo esc_html($s['title']);?></h2><p><?php echo esc_html($s['subtitle']);?></p></div><?php if(!empty($s['show_arrows'])):?><div><button class="am-prev" type="button" aria-label="قبلی">‹</button><button class="am-next" type="button" aria-label="بعدی">›</button></div><?php endif;?></header><div class="am-viewport"><div class="am-track"><?php $colors=['#F0B900','#E83E8C','#08B8D8','#9B4DFF'];$i=0;while($q->have_posts()):$q->the_post();$color=$colors[$i++%count($colors)];$cats=get_the_category();?><article class="am-card" style="--am-accent:<?php echo esc_attr($color);?>"><a class="am-image" href="<?php the_permalink();?>"><?php if(has_post_thumbnail())the_post_thumbnail('medium_large',['loading'=>'lazy']);?><i></i><?php if(!empty($s['show_date'])):?><time><?php echo esc_html(get_the_date('j M'));?></time><?php endif;?><?php if($cats):?><span><?php echo esc_html($cats[0]->name);?></span><?php endif;?></a><div class="am-body"><h3><a href="<?php the_permalink();?>"><?php the_title();?></a></h3><?php if(!empty($s['show_excerpt'])):?><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),16,'…'));?></p><?php endif;?><footer><div class="am-actions"><?php if(!empty($s['show_like'])):?><button class="am-like" type="button" data-post="<?php echo esc_attr(get_the_ID());?>" aria-label="پسندیدن"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21.2l7.8-7.8a5.5 5.5 0 0 0 1-7.8Z"/></svg><small><?php echo absint(get_post_meta(get_the_ID(),'_alookhor_likes',true));?></small></button><?php endif;?><?php if(!empty($s['show_save'])):?><button class="am-save" type="button" data-post="<?php echo esc_attr(get_the_ID());?>" aria-label="ذخیره مطلب"><svg viewBox="0 0 24 24"><path d="m19 21-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2Z"/></svg></button><?php endif;?></div><a class="am-more" href="<?php the_permalink();?>"><?php echo esc_html($s['button_text']);?> ←</a></footer></div></article><?php endwhile;wp_reset_postdata();?></div></div></div></section><?php return ob_get_clean();}
add_shortcode('alookhor_magazine','alookhor_cc_magazine_shortcode');
add_action('wp_ajax_alookhor_magazine_like','alookhor_cc_magazine_like');add_action('wp_ajax_nopriv_alookhor_magazine_like','alookhor_cc_magazine_like');
function alookhor_cc_magazine_like(){check_ajax_referer('alookhor_magazine_like','nonce');$id=absint($_POST['post_id']??0);if(!$id||get_post_type($id)!=='post')wp_send_json_error(['message'=>'نوشته نامعتبر است'],400);$likes=absint(get_post_meta($id,'_alookhor_likes',true))+1;update_post_meta($id,'_alookhor_likes',$likes);wp_send_json_success(['likes'=>$likes]);}
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-magazine',ALOOKHOR_CC_URL.'assets/css/frontend-magazine.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-magazine',ALOOKHOR_CC_URL.'assets/js/frontend-magazine.js',[],ALOOKHOR_CC_BUILD,true);wp_localize_script('alookhor-cc-magazine','ALOOKHOR_MAGAZINE',['ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('alookhor_magazine_like')]);});
