<?php
/** Professional newsletter — [alookhor_newsletter]. */
if(!defined('ABSPATH'))exit;
function alookhor_cc_newsletter_defaults(){return ['enabled'=>true,'kicker'=>'باشگاه مشتریان آلوخور','title'=>'از تخفیف‌ها و محصولات جدید باخبر شوید','description'=>'با عضویت در خبرنامه، اولین نفری باشید که از جدیدترین محصولات، تخفیف‌های طلایی و اخبار خشکبار مطلع می‌شود.','placeholder'=>'ایمیل خود را وارد کنید…','button_text'=>'عضویت','success_text'=>'عضویت شما با موفقیت ثبت شد.','privacy_text'=>'با ثبت ایمیل، قوانین حریم خصوصی را می‌پذیرم.','background'=>'#43082F','surface'=>'#54133D','gold'=>'#D8A927','text'=>'#FFFFFF','muted'=>'#D4BECB','radius'=>18];}
function alookhor_cc_get_newsletter_settings(){$state=alookhor_cc_get_settings();$saved=is_array($state['newsletter_settings']??null)?$state['newsletter_settings']:[];return array_replace(alookhor_cc_newsletter_defaults(),$saved);}
function alookhor_cc_newsletter_shortcode(){$s=alookhor_cc_get_newsletter_settings();if(empty($s['enabled']))return '';$c=[];foreach(['background','surface','gold','text','muted'] as $k)$c[$k]=sanitize_hex_color($s[$k]??'')?:alookhor_cc_newsletter_defaults()[$k];ob_start();static $style=false;if(!$style){$style=true;$f=ALOOKHOR_CC_DIR.'assets/css/frontend-newsletter.css';if(file_exists($f))echo '<style id="alookhor-newsletter-inline">'.file_get_contents($f).'</style>';}?>
<section class="alookhor-newsletter" dir="rtl" style="--an-bg:<?php echo esc_attr($c['background']);?>;--an-surface:<?php echo esc_attr($c['surface']);?>;--an-gold:<?php echo esc_attr($c['gold']);?>;--an-text:<?php echo esc_attr($c['text']);?>;--an-muted:<?php echo esc_attr($c['muted']);?>;--an-radius:<?php echo max(8,min(40,absint($s['radius'])));?>px"><div class="an-inner"><div class="an-copy"><span><?php echo esc_html($s['kicker']);?></span><h2><?php echo esc_html($s['title']);?></h2><p><?php echo esc_html($s['description']);?></p></div><form class="an-form" novalidate><div><input type="email" name="email" required autocomplete="email" placeholder="<?php echo esc_attr($s['placeholder']);?>"><button type="submit"><?php echo esc_html($s['button_text']);?></button></div><label><input type="checkbox" required> <?php echo esc_html($s['privacy_text']);?></label><p class="an-message" aria-live="polite" data-success="<?php echo esc_attr($s['success_text']);?>"></p><input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('alookhor_newsletter'));?>"></form></div></section><?php return ob_get_clean();}
add_shortcode('alookhor_newsletter','alookhor_cc_newsletter_shortcode');
add_action('wp_ajax_alookhor_newsletter_subscribe','alookhor_cc_newsletter_subscribe');add_action('wp_ajax_nopriv_alookhor_newsletter_subscribe','alookhor_cc_newsletter_subscribe');
function alookhor_cc_newsletter_subscribe(){check_ajax_referer('alookhor_newsletter','nonce');$email=sanitize_email(wp_unslash($_POST['email']??''));if(!$email||!is_email($email))wp_send_json_error(['message'=>'ایمیل معتبر وارد کنید.'],422);$list=get_option('alookhor_newsletter_subscribers',[]);if(!is_array($list))$list=[];$hash=hash('sha256',strtolower($email));if(!isset($list[$hash])){$list[$hash]=['email'=>$email,'created_at'=>current_time('mysql')];update_option('alookhor_newsletter_subscribers',$list,false);}wp_send_json_success(['message'=>alookhor_cc_get_newsletter_settings()['success_text']]);}
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('alookhor-cc-newsletter',ALOOKHOR_CC_URL.'assets/css/frontend-newsletter.css',[],ALOOKHOR_CC_BUILD);wp_enqueue_script('alookhor-cc-newsletter',ALOOKHOR_CC_URL.'assets/js/frontend-newsletter.js',[],ALOOKHOR_CC_BUILD,true);wp_localize_script('alookhor-cc-newsletter','ALOOKHOR_NEWSLETTER',['ajax_url'=>admin_url('admin-ajax.php')]);});
